# import pandas

In [17]:
import pandas as pd

### create data frame

In [18]:
df = pd.DataFrame (
    {
        "Name": ['erfan', 'parsa', 'sirous'],
        "Age": [20, 22, 40],
        "Gender": ['male', 'male', 'male'],
        "Ghad": [180, 170, 195],
    }
)

print(df)

     Name  Age Gender  Ghad
0   erfan   20   male   180
1   parsa   22   male   170
2  sirous   40   male   195

### create series (one columns)

In [ ]:
mive = pd.Series(['orange', 'apple', 'banana'], name = 'mive')

print(mive)

0    orange
1     apple
2    banana
Name: mive, dtype: str

### some functions

In [20]:
print(df["Age"].max())
print(df["Age"].min())
print(df["Age"].mean())
print(df["Age"].std())

40
20
27.333333333333332
11.015141094572204

### general discribe

In [21]:
df.describe()

             Age        Ghad
count   3.000000    3.000000
mean   27.333333  181.666667
std    11.015141   12.583057
min    20.000000  170.000000
25%    21.000000  175.000000
50%    22.000000  180.000000
75%    31.000000  187.500000
max    40.000000  195.000000

In [22]:
df.describe(include= "all")

         Name        Age Gender        Ghad
count       3   3.000000      3    3.000000
unique      3        NaN      1         NaN
top     erfan        NaN   male         NaN
freq        1        NaN      3         NaN
mean      NaN  27.333333    NaN  181.666667
std       NaN  11.015141    NaN   12.583057
min       NaN  20.000000    NaN  170.000000
25%       NaN  21.000000    NaN  175.000000
50%       NaN  22.000000    NaN  180.000000
75%       NaN  31.000000    NaN  187.500000
max       NaN  40.000000    NaN  195.000000

In [23]:
df.describe(include= "object")

C:\Users\erfan\AppData\Local\Temp\ipykernel_13520\3501404678.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include= "object")

         Name Gender
count       3      3
unique      3      1
top     erfan   male
freq        1      3

In [32]:
df.describe(include= "number")

             Age        Ghad
count   3.000000    3.000000
mean   27.333333  181.666667
std    11.015141   12.583057
min    20.000000  170.000000
25%    21.000000  175.000000
50%    22.000000  180.000000
75%    31.000000  187.500000
max    40.000000  195.000000

# import numpy

In [ ]:
import numpy as np

### generating random number with numpy

In [33]:
s = pd.Series(np.random.randn(1000))

s.describe()

count    1000.000000
mean        0.005133
std         0.997104
min        -2.995863
25%        -0.662211
50%         0.033343
75%         0.671134
max         3.190387
dtype: float64

### filtering data with nan

In [34]:
s[::2] = np.nan

s.describe()

count    500.000000
mean      -0.039015
std        0.963245
min       -2.995863
25%       -0.675026
50%        0.018376
75%        0.611550
max        3.159406
dtype: float64

### create data frame with numpy random number

In [35]:
ss = pd.DataFrame(np.random.randn(1000, 5), columns= ['a', 'b', 'c', 'd', 'e'])

ss

            a         b         c         d         e
0   -1.069504 -0.495640  0.948329 -1.713486  0.336995
1   -1.087897 -0.819708  0.437140 -0.119287  0.473668
2    0.637131 -0.678926 -0.349351  0.459575 -0.468636
3   -0.176358 -0.514418 -0.929415 -0.762672 -0.087152
4    1.923503 -1.455725  1.222143 -1.717834 -1.639405
..        ...       ...       ...       ...       ...
995 -0.661541  0.835234  0.969158  0.139060  0.803566
996 -0.570746 -0.994898 -0.515975 -1.478638 -0.083450
997  0.495907 -1.152791  1.160437  0.085347  1.267331
998  1.113635 -0.183759  0.591120 -0.386288 -0.652458
999 -0.966548  0.745053  0.978912  0.674451  0.950055

[1000 rows x 5 columns]

In [36]:
ss.describe()

                 a            b            c            d            e
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.044713     0.038983    -0.039869    -0.008986     0.026380
std       0.997235     0.967454     0.968605     1.037087     0.998243
min      -2.633489    -2.894957    -3.249026    -3.345788    -3.371780
25%      -0.728915    -0.647523    -0.635551    -0.723469    -0.625971
50%      -0.047079     0.045271    -0.032664    -0.018123    -0.000313
75%       0.581121     0.715237     0.591671     0.718523     0.725475
max       3.126903     3.002697     4.383045     3.002821     2.822670

In [38]:
a = pd.Series(['a', 'b', 'b', 'a', 'c'])
print(a)
a.describe()

0    a
1    b
2    b
3    a
4    c
dtype: str

count     5
unique    3
top       a
freq      2
dtype: object