# import pandas and numpy

In [46]:
import numpy as np
import pandas as pd

### create data range with pandas

In [47]:
dates = pd.date_range('20230101', periods=6)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[us]', freq='D')

### create data frame

In [48]:
df = pd.DataFrame(np.random.randn(6, 4), index= dates, columns=list('ABCD'))
df

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

### some functions

In [49]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [50]:
df['A']

2023-01-01   -0.810053
2023-01-02   -0.079671
2023-01-03    0.693437
2023-01-04   -2.063825
2023-01-05   -1.040085
2023-01-06   -0.095446
Freq: D, Name: A, dtype: float64

In [51]:
df.head()

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510

In [52]:
df.head(2)

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240

In [53]:
df.A

2023-01-01   -0.810053
2023-01-02   -0.079671
2023-01-03    0.693437
2023-01-04   -2.063825
2023-01-05   -1.040085
2023-01-06   -0.095446
Freq: D, Name: A, dtype: float64

In [54]:
df.tail(2)

                   A         B         C         D
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

In [55]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.565940 -0.234710  0.397507  0.024636
std    0.956234  0.437984  1.651662  0.733045
min   -2.063825 -0.723358 -1.727305 -1.320510
25%   -0.982577 -0.524090 -0.741312 -0.151408
50%   -0.452750 -0.351156  0.705354  0.318368
75%   -0.083614  0.049031  0.997890  0.422604
max    0.693437  0.416720  2.829769  0.682240

In [56]:
df.mean()

A   -0.565940
B   -0.234710
C    0.397507
D    0.024636
dtype: float64

In [57]:
df['A'].mean()

np.float64(-0.5659403885785003)

In [58]:
df[1: 3]

                   A         B         C         D
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678

In [59]:
df.T

   2023-01-01  2023-01-02  2023-01-03  2023-01-04  2023-01-05  2023-01-06
A   -0.810053   -0.079671    0.693437   -2.063825   -1.040085   -0.095446
B   -0.195936   -0.506376    0.130687   -0.723358    0.416720   -0.529995
C   -1.200783   -1.727305    2.829769    1.072651    0.637099    0.773609
D   -0.283437    0.682240    0.244678    0.392057   -1.320510    0.432786

In [60]:
df.sort_values(by='B', ascending=False)
# ascending=True for ascending order, ascending=False for descending order

                   A         B         C         D
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-06 -0.095446 -0.529995  0.773609  0.432786
2023-01-04 -2.063825 -0.723358  1.072651  0.392057

### filtering by comparator

In [61]:
df[df['A'] > 0]

                   A         B         C         D
2023-01-03  0.693437  0.130687  2.829769  0.244678

### some function and method

In [62]:
print(df.head()) # first 5 rows
print(df.head(10)) # first 10 rows
print(df.tail()) # last 5 rows
print(df.info()) # information about the DataFrame
print(df.describe()) # statistical summary of the DataFrame
print(df.shape) # shape of the DataFrame (rows, columns)
print(df.columns) # column names

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786
                   A         B         C         D
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786
<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2023-01-01 to 2023-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes
None
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.565940 -0.234710  0.397507  0.024636
std    0.956234  0.437984  1.651662  0.733045
min   -2.063825 -0.723358 -1.727305 -1.320510
25%   -0.982577 -0.524090 -0.741312 -0.151408
50%   -0.452750 -0.351156  0.705354  0.318368
75%   -0.083614  0.049031  0.997890  0.422604
max    0.693437  0.416720  2.829769  0.682240
(6, 4)
Index(['A', 'B', 'C', 'D'], dtype='str')

### selecting columns and rows

In [63]:
print(df['A']) # select column A
print(df[['A']]) # select column A as a DataFrame
print(df[['A', 'B']]) # select columns A and B as a DataFrame

print(df[0:3]) # select first 3 rows
print(df.loc['2023-01-01']) # select row by label
print(df.loc[dates[0]]) # select row by label
print(df.loc[:, ['A', 'B']]) # select all rows and columns A and B
print(df.loc['2023-01-01', ['A', 'B']]) # select row by label and columns A and B
print(df.iloc[3]) # select row by integer position
print(df.iloc[3:5, 0:2]) # select rows 3 to

2023-01-01   -0.810053
2023-01-02   -0.079671
2023-01-03    0.693437
2023-01-04   -2.063825
2023-01-05   -1.040085
2023-01-06   -0.095446
Freq: D, Name: A, dtype: float64
                   A
2023-01-01 -0.810053
2023-01-02 -0.079671
2023-01-03  0.693437
2023-01-04 -2.063825
2023-01-05 -1.040085
2023-01-06 -0.095446
                   A         B
2023-01-01 -0.810053 -0.195936
2023-01-02 -0.079671 -0.506376
2023-01-03  0.693437  0.130687
2023-01-04 -2.063825 -0.723358
2023-01-05 -1.040085  0.416720
2023-01-06 -0.095446 -0.529995
                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
A   -0.810053
B   -0.195936
C   -1.200783
D   -0.283437
Name: 2023-01-01 00:00:00, dtype: float64
A   -0.810053
B   -0.195936
C   -1.200783
D   -0.283437
Name: 2023-01-01 00:00:00, dtype: float64
                   A         B
2023-01-01 -0.810053 -0.195936
2023-01-02 -0.079671 -0.506376
2023-01-03  0.693437  0.130687
2023-01-04 -2.063825 -0.723358
2023-01-05 -1.040085  0.416720
2023-01-06 -0.095446 -0.529995
A   -0.810053
B   -0.195936
Name: 2023-01-01 00:00:00, dtype: float64
A   -2.063825
B   -0.723358
C    1.072651
D    0.392057
Name: 2023-01-04 00:00:00, dtype: float64
                   A         B
2023-01-04 -2.063825 -0.723358
2023-01-05 -1.040085  0.416720

### read and write operations

In [64]:
df.to_csv("C:/Users/erfan/Desktop/olamp/python learn/learning-numpy-pandas/dataframe.csv")

In [65]:
df.to_excel("C:/Users/erfan/Desktop/olamp/python learn/learning-numpy-pandas/dataframe.xlsx", sheet_name='Sheet1')

In [66]:
df = pd.read_csv("dataframe.csv")