# import numpy and pandas

In [559]:
import numpy as np
import pandas as pd

### read csv data frame

In [560]:
sdataframe = pd.read_csv("dataframe.csv")
df = pd.read_csv("dataframe.csv", index_col=0) # read csv file and set the first column as index

In [561]:
df

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

### fixing data frame

In [562]:
sdataframe

   Unnamed: 0         A         B         C         D
0  2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
1  2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2  2023-01-03  0.693437  0.130687  2.829769  0.244678
3  2023-01-04 -2.063825 -0.723358  1.072651  0.392057
4  2023-01-05 -1.040085  0.416720  0.637099 -1.320510
5  2023-01-06 -0.095446 -0.529995  0.773609  0.432786

In [563]:
sdataframe = sdataframe.set_index('Unnamed: 0') # set the first column as index

In [564]:
sdataframe

                   A         B         C         D
Unnamed: 0
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

In [565]:
sdataframe.index.name = None # remove the name of the index column

In [566]:
sdataframe

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

### change column name

In [567]:
sdataframe = sdataframe.rename(columns= {'A': 'ali', 'B': 'ahmad'}) # rename columns
sdataframe

                 ali     ahmad         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

### initial look at the data

In [568]:
df.head() # first 5 rows
df.head(10) # first 10 rows
df.tail() # last 5 rows
df.shape # number of rows and columns
df.info() # information about the dataframe
df.describe() # statistical summary of the dataframe
df.columns # list of column names
df.index # index of the dataframe

<class 'pandas.DataFrame'>
Index: 6 entries, 2023-01-01 to 2023-01-06
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0+ bytes

Index(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
       '2023-01-06'],
      dtype='str')

### selecting columns and rows

In [569]:
df['A'] # access column A , returns a pandas Series
df[['A', 'B']] # access columns A and B , returns a pandas DataFrame

# df.loc[0] # access row with index 0 , returns a pandas Series
# df.loc[0:2] # access rows with index 0 to 2 , returns a pandas DataFrame
df.iloc[0] # access row at position 0 , returns a pandas Series
df.iloc[0:2] # access rows at position 0 to 2 , returns

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240

### filtering by conditin
### (boolean filtering)

In [570]:
df[df['A'] > 0] # access rows where column A is greater than 0
df[df['B'] == 1] # access rows where column B is equal to 1
df[(df['A'] > 0) & (df['B'] == 1)] # access rows where column A is greater than 0 and column B is equal to 1    
df[(df['A'] > 0) | (df['B'] == 1)] # access rows where column A is greater than 0 or column B is equal to 1

                   A         B         C         D
2023-01-03  0.693437  0.130687  2.829769  0.244678

### checking for missing values

In [571]:
df.isnull() # check for missing values

                A      B      C      D
2023-01-01  False  False  False  False
2023-01-02  False  False  False  False
2023-01-03  False  False  False  False
2023-01-04  False  False  False  False
2023-01-05  False  False  False  False
2023-01-06  False  False  False  False

In [572]:
df.isnull().sum() # count of null values in each column

A    0
B    0
C    0
D    0
dtype: int64

In [573]:
df.dropna() # drop rows with missing values

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

In [574]:
df.fillna(0) # fill missing values with 0

                   A         B         C         D
2023-01-01 -0.810053 -0.195936 -1.200783 -0.283437
2023-01-02 -0.079671 -0.506376 -1.727305  0.682240
2023-01-03  0.693437  0.130687  2.829769  0.244678
2023-01-04 -2.063825 -0.723358  1.072651  0.392057
2023-01-05 -1.040085  0.416720  0.637099 -1.320510
2023-01-06 -0.095446 -0.529995  0.773609  0.432786

In [575]:
# fill missing values in column A with the mean of column A
df['A'].fillna(df['A'].mean())

2023-01-01   -0.810053
2023-01-02   -0.079671
2023-01-03    0.693437
2023-01-04   -2.063825
2023-01-05   -1.040085
2023-01-06   -0.095446
Name: A, dtype: float64

### categorical columns

In [576]:
df['A'].value_counts() # count of unique values in column A
df['A'].unique() # unique values in column A
df['A'].nunique() # number of unique values in column A

6

### groupby

In [577]:
# group by column A and calculate the mean of column B for each group
df.groupby('A')['B'].mean()

A
-2.063825   -0.723358
-1.040085    0.416720
-0.810053   -0.195936
-0.095446   -0.529995
-0.079671   -0.506376
 0.693437    0.130687
Name: B, dtype: float64

In [578]:
# group by column A and calculate the mean and count of column B for each group
df.groupby('A')['B'].agg(['mean', 'count'])

               mean  count
A
-2.063825 -0.723358      1
-1.040085  0.416720      1
-0.810053 -0.195936      1
-0.095446 -0.529995      1
-0.079671 -0.506376      1
 0.693437  0.130687      1

In [579]:
# create a new dataframe with transaction_amount, ip_risk_score, and payment_method columns
gdf = pd.DataFrame(
    {
        'transaction_amount' : [50, 1500, 200, 3000],
        'ip_risk_score' : [0.1, 0.9, 0.3, 0.8],
        'payment_method' : ['credit_card', 'paypal', 'credit_card', 'paypal']
    }
)
gdf

   transaction_amount  ip_risk_score payment_method
0                  50            0.1    credit_card
1                1500            0.9         paypal
2                 200            0.3    credit_card
3                3000            0.8         paypal

In [580]:
# statistical summary of the dataframe for numeric columns
gdf.describe(include= 'all')

        transaction_amount  ip_risk_score payment_method
count             4.000000       4.000000              4
unique                 NaN            NaN              2
top                    NaN            NaN    credit_card
freq                   NaN            NaN              2
mean           1187.500000       0.525000            NaN
std            1372.573617       0.386221            NaN
min              50.000000       0.100000            NaN
25%             162.500000       0.250000            NaN
50%             850.000000       0.550000            NaN
75%            1875.000000       0.825000            NaN
max            3000.000000       0.900000            NaN

In [581]:
# group by payment_method and calculate the mean of transaction_amount for each group
mean_result = gdf.groupby('payment_method')['transaction_amount'].mean()
print(mean_result)

payment_method
credit_card     125.0
paypal         2250.0
Name: transaction_amount, dtype: float64

In [582]:
# group by payment_method and calculate the mean and count of transaction_amount for each group
mc_result = gdf.groupby('payment_method')['transaction_amount'].agg(['mean', 'count'])
print(mc_result)

                  mean  count
payment_method
credit_card      125.0      2
paypal          2250.0      2

In [583]:
# group by payment_method and calculate the mean of ip_risk_score for each group
iprisk_gdf = gdf.groupby('payment_method')['ip_risk_score'].mean()
print(iprisk_gdf)

payment_method
credit_card    0.20
paypal         0.85
Name: ip_risk_score, dtype: float64

In [584]:
# group by payment_method and calculate the mean and count of ip_risk_score for each group
mcIprisk_gdf = gdf.groupby('payment_method')['ip_risk_score'].agg(['mean', 'count'])
print(mcIprisk_gdf)

                mean  count
payment_method
credit_card     0.20      2
paypal          0.85      2

In [585]:
# group by payment_method and calculate the mean of all numeric columns for each group
gdf.groupby('payment_method').mean()

                transaction_amount  ip_risk_score
payment_method
credit_card                  125.0           0.20
paypal                      2250.0           0.85

In [586]:
gdf.groupby('payment_method').agg(['mean', 'count'])

               transaction_amount       ip_risk_score
                             mean count          mean count
payment_method
credit_card                 125.0     2          0.20     2
paypal                     2250.0     2          0.85     2

### create new columns
### basic feature engineering

In [587]:
new_df = pd.DataFrame(
    {
        'transaction_amount' : [50, 1500, 200, 3000],
        'ip_risk_score' : [0.1, 0.9, 0.2, 0.8]
    }
)

new_df

   transaction_amount  ip_risk_score
0                  50            0.1
1                1500            0.9
2                 200            0.2
3                3000            0.8

In [588]:
new_df['amount_log'] = np.log(new_df['transaction_amount']) # add a new column with the log of transaction_amount
new_df

   transaction_amount  ip_risk_score  amount_log
0                  50            0.1    3.912023
1                1500            0.9    7.313220
2                 200            0.2    5.298317
3                3000            0.8    8.006368

In [589]:
new_df['is_expensive'] = new_df['transaction_amount'] > 1000 # add a new column with boolean values indicating if the transaction is expensive
new_df

   transaction_amount  ip_risk_score  amount_log  is_expensive
0                  50            0.1    3.912023         False
1                1500            0.9    7.313220          True
2                 200            0.2    5.298317         False
3                3000            0.8    8.006368          True

In [590]:
new_df['risk_category'] = new_df['ip_risk_score'].apply(
    lambda x : 'high' if x > 0.6 else 'low'
)
new_df

   transaction_amount  ip_risk_score  amount_log  is_expensive risk_category
0                  50            0.1    3.912023         False           low
1                1500            0.9    7.313220          True          high
2                 200            0.2    5.298317         False           low
3                3000            0.8    8.006368          True          high

### merg

In [591]:
merged_df = pd.merge(gdf, new_df, on= 'transaction_amount') # merge two dataframes on transaction_amount column
merged_df

,transaction_amount,ip_risk_score_x,payment_method,ip_risk_score_y,amount_log,is_expensive,risk_category
0,50,0.1,credit_card,0.1,3.912023,False,low
1,1500,0.9,paypal,0.9,7.313220,True,high
2,200,0.3,credit_card,0.2,5.298317,False,low
3,3000,0.8,paypal,0.8,8.006368,True,high

In [592]:
new_merged_df = gdf.merge(new_df, on= 'transaction_amount', how= 'left') # merge two dataframes on transaction_amount column with left join
new_merged_df

,transaction_amount,ip_risk_score_x,payment_method,ip_risk_score_y,amount_log,is_expensive,risk_category
0,50,0.1,credit_card,0.1,3.912023,False,low
1,1500,0.9,paypal,0.9,7.313220,True,high
2,200,0.3,credit_card,0.2,5.298317,False,low
3,3000,0.8,paypal,0.8,8.006368,True,high

### working with dates

In [593]:
gdf

   transaction_amount  ip_risk_score payment_method
0                  50            0.1    credit_card
1                1500            0.9         paypal
2                 200            0.3    credit_card
3                3000            0.8         paypal

In [594]:
date = ['2024-03-15 08:30:00', '2024-03-16 23:45:00', '2024-03-22 10:15:00', '2024-03-23 14:10:00']
gdf['transaction_date'] = date # add a new column with transaction dates
print(gdf)
print(gdf.dtypes) # print the data types of each column

   transaction_amount  ip_risk_score payment_method     transaction_date
0                  50            0.1    credit_card  2024-03-15 08:30:00
1                1500            0.9         paypal  2024-03-16 23:45:00
2                 200            0.3    credit_card  2024-03-22 10:15:00
3                3000            0.8         paypal  2024-03-23 14:10:00
transaction_amount      int64
ip_risk_score         float64
payment_method            str
transaction_date          str
dtype: object

In [595]:
# convert the transaction_date column to datetime format
gdf['transaction_date'] = pd.to_datetime(gdf['transaction_date'])

print(gdf)
print(gdf.dtypes) # print the data types of each column

   transaction_amount  ip_risk_score payment_method    transaction_date
0                  50            0.1    credit_card 2024-03-15 08:30:00
1                1500            0.9         paypal 2024-03-16 23:45:00
2                 200            0.3    credit_card 2024-03-22 10:15:00
3                3000            0.8         paypal 2024-03-23 14:10:00
transaction_amount             int64
ip_risk_score                float64
payment_method                   str
transaction_date      datetime64[us]
dtype: object

In [596]:
gdf['hour'] = gdf['transaction_date'].dt.hour # add a new column with the hour of the transaction
gdf['day_of_week'] = gdf['transaction_date'].dt.dayofweek # add a new column with the day of the week of the transaction (0=Monday, 6=Sunday)
gdf['day_name'] = gdf['transaction_date'].dt.day_name() # add a new column with the name of the day of the week of the transaction
gdf['month'] = gdf['transaction_date'].dt.month # add a new column with the month of the transaction
gdf['date_only'] = gdf['transaction_date'].dt.date # add a new column with the date of the transaction

gdf

,transaction_amount,ip_risk_score,payment_method,transaction_date,hour,day_of_week,day_name,month,date_only
0,50,0.1,credit_card,2024-03-15 08:30:00,8,4,Friday,3,2024-03-15
1,1500,0.9,paypal,2024-03-16 23:45:00,23,5,Saturday,3,2024-03-16
2,200,0.3,credit_card,2024-03-22 10:15:00,10,4,Friday,3,2024-03-22
3,3000,0.8,paypal,2024-03-23 14:10:00,14,5,Saturday,3,2024-03-23

In [597]:
fdf = pd.DataFrame({
    'pickup': ['2024-03-15 08:00:00', '2024-03-16 10:00:00'],
    'dropoff': ['2024-03-15 08:25:00', '2024-03-17 10:50:00']
})
fdf['pickup'] = pd.to_datetime(fdf['pickup'])
fdf['dropoff'] = pd.to_datetime(fdf['dropoff'])

fdf['duration'] = fdf['dropoff'] - fdf['pickup'] # add a new column with the duration of the trip
fdf

               pickup             dropoff        duration
0 2024-03-15 08:00:00 2024-03-15 08:25:00 0 days 00:25:00
1 2024-03-16 10:00:00 2024-03-17 10:50:00 1 days 00:50:00

### sortig and remove columns

In [598]:
ndf = gdf.copy() # create a copy of the dataframe to avoid modifying the original dataframe
ndf = ndf.sort_values('transaction_amount', ascending=False) # sort the dataframe by transaction_amount in descending order
ndf

,transaction_amount,ip_risk_score,payment_method,transaction_date,hour,day_of_week,day_name,month,date_only
3,3000,0.8,paypal,2024-03-23 14:10:00,14,5,Saturday,3,2024-03-23
1,1500,0.9,paypal,2024-03-16 23:45:00,23,5,Saturday,3,2024-03-16
2,200,0.3,credit_card,2024-03-22 10:15:00,10,4,Friday,3,2024-03-22
0,50,0.1,credit_card,2024-03-15 08:30:00,8,4,Friday,3,2024-03-15

In [599]:
ndf = ndf.reset_index(drop= True) # reset the index of the dataframe and drop the old index
ndf

,transaction_amount,ip_risk_score,payment_method,transaction_date,hour,day_of_week,day_name,month,date_only
0,3000,0.8,paypal,2024-03-23 14:10:00,14,5,Saturday,3,2024-03-23
1,1500,0.9,paypal,2024-03-16 23:45:00,23,5,Saturday,3,2024-03-16
2,200,0.3,credit_card,2024-03-22 10:15:00,10,4,Friday,3,2024-03-22
3,50,0.1,credit_card,2024-03-15 08:30:00,8,4,Friday,3,2024-03-15

In [600]:
ndf = ndf.drop('transaction_date', axis= 1) # drop the transaction_date column from the dataframe
ndf

,transaction_amount,ip_risk_score,payment_method,hour,day_of_week,day_name,month,date_only
0,3000,0.8,paypal,14,5,Saturday,3,2024-03-23
1,1500,0.9,paypal,23,5,Saturday,3,2024-03-16
2,200,0.3,credit_card,10,4,Friday,3,2024-03-22
3,50,0.1,credit_card,8,4,Friday,3,2024-03-15

In [601]:
ndf.drop([1, 3]) # drop rows with index

,transaction_amount,ip_risk_score,payment_method,hour,day_of_week,day_name,month,date_only
0,3000,0.8,paypal,14,5,Saturday,3,2024-03-23
2,200,0.3,credit_card,10,4,Friday,3,2024-03-22

In [602]:
# drop rows where transaction_amount is less than 1000
ndf.drop(ndf[ndf['transaction_amount'] < 1000].index, inplace=True)

### correlation between columns

In [603]:
sdf = gdf.copy() # create a copy of the dataframe to avoid modifying the original dataframe
sdf

,transaction_amount,ip_risk_score,payment_method,transaction_date,hour,day_of_week,day_name,month,date_only
0,50,0.1,credit_card,2024-03-15 08:30:00,8,4,Friday,3,2024-03-15
1,1500,0.9,paypal,2024-03-16 23:45:00,23,5,Saturday,3,2024-03-16
2,200,0.3,credit_card,2024-03-22 10:15:00,10,4,Friday,3,2024-03-22
3,3000,0.8,paypal,2024-03-23 14:10:00,14,5,Saturday,3,2024-03-23

In [604]:
sdf.select_dtypes(include='number').corr()

,transaction_amount,ip_risk_score,hour,day_of_week,month
transaction_amount,1.000000,0.830792,0.496051,0.893846,NaN
ip_risk_score,0.830792,1.000000,0.885501,0.971666,NaN
hour,0.496051,0.885501,1.000000,0.824530,NaN
day_of_week,0.893846,0.971666,0.824530,1.000000,NaN
month,NaN,NaN,NaN,NaN,NaN

In [605]:
sdf.corr(numeric_only=True)['transaction_amount'] # correlation of transaction_amount with other numeric columns

transaction_amount    1.000000
ip_risk_score         0.830792
hour                  0.496051
day_of_week           0.893846
month                      NaN
Name: transaction_amount, dtype: float64

### encoding

In [606]:
sdf

,transaction_amount,ip_risk_score,payment_method,transaction_date,hour,day_of_week,day_name,month,date_only
0,50,0.1,credit_card,2024-03-15 08:30:00,8,4,Friday,3,2024-03-15
1,1500,0.9,paypal,2024-03-16 23:45:00,23,5,Saturday,3,2024-03-16
2,200,0.3,credit_card,2024-03-22 10:15:00,10,4,Friday,3,2024-03-22
3,3000,0.8,paypal,2024-03-23 14:10:00,14,5,Saturday,3,2024-03-23

In [607]:
sdf = sdf.drop('transaction_date', axis= 1)
sdf

,transaction_amount,ip_risk_score,payment_method,hour,day_of_week,day_name,month,date_only
0,50,0.1,credit_card,8,4,Friday,3,2024-03-15
1,1500,0.9,paypal,23,5,Saturday,3,2024-03-16
2,200,0.3,credit_card,10,4,Friday,3,2024-03-22
3,3000,0.8,paypal,14,5,Saturday,3,2024-03-23

In [611]:
encoded = pd.get_dummies(sdf, columns=['payment_method', 'day_name'])
encoded

,transaction_amount,ip_risk_score,hour,day_of_week,month,date_only,payment_method_credit_card,payment_method_paypal,day_name_Friday,day_name_Saturday
0,50,0.1,8,4,3,2024-03-15,True,False,True,False
1,1500,0.9,23,5,3,2024-03-16,False,True,False,True
2,200,0.3,10,4,3,2024-03-22,True,False,True,False
3,3000,0.8,14,5,3,2024-03-23,False,True,False,True

In [616]:
sdf.dtypes

transaction_amount      int64
ip_risk_score         float64
payment_method            str
hour                    int32
day_of_week             int32
day_name                  str
month                   int32
date_only              object
dtype: object